/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_secmem_remoteroid_natives_FrameHandler */

#ifndef _Included_org_secmem_remoteroid_natives_FrameHandler
#define _Included_org_secmem_remoteroid_natives_FrameHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_secmem_remoteroid_natives_FrameHandler
 * Method:    readFrameBufferNative
 * Signature: (III[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_secmem_remoteroid_natives_FrameHandler_readFrameBufferNative
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
