/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_secmem_remoteroid_natives_InputHandler */

#ifndef _Included_org_secmem_remoteroid_natives_InputHandler
#define _Included_org_secmem_remoteroid_natives_InputHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_secmem_remoteroid_natives_InputHandler
 * Method:    keyEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_secmem_remoteroid_natives_InputHandler_keyEvent
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
